baseurl = "/"
languageCode = "en-us"
title = "Homepage"

[menu]

  ###################
  # Main Menu (nav) #
  ###################

  # Home

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = -120

  [[menu.main]]
    identifier = "about"
    name = "About Us"
    weight = -115
    url = "/about"

  [[menu.main]]
    identifier = "get_involved"
    name = "Get Involved"
    weight = -110
    url = "/get_involved"

  #  Blog
  [[menu.main]]
    identifier = "post"
    name = "Blog"
    url = "/post"
    weight = -105

  # For Members
  [[menu.main]]
    identifier = "for_members"
    name = "For Members"
    weight = -100
    url = "/for_members"
  
  ###############
  # Footer menu #
  ###############

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = -120

  # About Section

  [[menu.main]]
    identifier = "about"
    name = "About Us"
    weight = -115
    url = "/about"

  # Get Involved Section

  [[menu.main]]
    identifier = "get_involved"
    name = "Get Involved"
    weight = -110
    url = "/get_involved"

  #  Blog
  [[menu.main]]
    identifier = "post"
    name = "Blog"
    url = "/post"
    weight = -105

  # For Members
  [[menu.main]]
    identifier = "for_members"
    name = "For Members"
    weight = -100
    url = "/for_members"
  