backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "campaign" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Campaign" # Used in the UI, ie.: "New Post"
    folder: "site/content/campaign" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Short Description", name: "summary", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "working_group" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Working Group" # Used in the UI, ie.: "New Post"
    folder: "site/content/working_group" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "for_members" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "For Members pages" # Used in the UI, ie.: "New Post"
    folder: "site/content/for_members" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string} 
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
      - file: "site/content/about/_index.md"
        label: "About Us"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string} 
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Definition of Democratic Socialism, name: democratic_socialism_definition, widget: text}
          - {label: Description of DSA, name: dsa_definition, widget: text}
          - label: Priorities
            name: priorities
            widget: list
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: text}
              - {label: Image, name: image, widget: image}
          - {label: Where the chapter covers, name: where, widget: text}
      - file: "site/content/for_members/_index.md"
        label: "For Members"
        name: "for_members"
        fields:
          - {label: Title, name: title, widget: string} 
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
      - file: "site/content/get_involved/_index.md"
        label: "Get Involved"
        name: "get_involved"
        fields:
          - {label: Title, name: title, widget: string} 
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Body", name: "body", widget: "markdown"}
